---
# tasks file for osp-keypair
  - name: Generate key files
    user:
      name: "{{ ansible_env.USER }}"
      generate_ssh_key: yes
      ssh_key_file: .ssh/openstack_key

  - os_keypair:
      cloud: ospcloud
      state: present
      name: ansible_ssh
      public_key_file: "{{ ansible_env.HOME }}/.ssh/openstack_key.pub"
