---
- name: Copy application WAR file to host
  copy:
    src: "{{ war_file }}"
    dest: /tmp

- name: Deployment of new application to JBoss
  jboss:
    deployment: "{{ app_name }}.war"
    deploy_path: /usr/share/jboss-as/standalone/deployments/
    src: "/tmp/{{ war_file }}"
    state: present
  when: upgrade == 'False'

- name: Upgrade Application
  jboss:
    deployment: "{{ app_name }}.war"
    deploy_path: /usr/share/jboss-as/standalone/deployments/
    src: "/tmp/{{ war_file }}"
    state: present
  when: upgrade == 'True'

- name: Sending notification email for App deployment
  mail:
    host: localhost
    port: 25
    to: Anthony Lin <anthony.lin.test@gmail.com>
    subject: Ansible Report for App Deployment
    body: "{{ app_name }} has been successfully deployed with {{ war_file }}"
  delegate_to: localhost
  when: upgrade == 'False'

- name: Sending notification email for App upgrade
  mail:
    host: localhost
    port: 25
    to: Anthony Lin <anthony.lin.test@gmail.com>
    subject: Ansible Report for App Upgrade
    body: "{{ app_name }} has been successfully upgraded with {{ war_file }}"
  delegate_to: localhost
  when: upgrade == 'True'
