$ANSIBLE_VAULT;1.1;AES256
33626166663461333035373563363538306266323865376536623534613734653633303662373139
3837366130333137333563666362346233653337653239620a646437663736626434633036336534
63616238336639313630306435326531383862303431393339323364616532333237313637346364
3738613265633535650a653965666335376330386539626430653762353034643730336163633132
36343130623064643631303433653335323032623333356638623238393463383164323538326433
65303766396363656337336535353863373331636331383038336238333432303936393264363634
30306239623430653863333730333834633133363063326236646466656230353666346331646432
35646661653963353265636161383434313663343764643439643136393566383665633436653366
37353863393438356537653935336562306561383530626332663762316538656131356562353362
3039376165383866643637363263303634393638313931363038
